Wow-Town/wowTown-frontend

src/App.css, src/App.js, src/components/Button.css, src/components/Button.js, src/components/Header.js, src/components/InputInfo.css, src/components/InputInfo.js, src/components/Logo.css, src/components/Logo.js, src/components/Navbar.js, src/pages/Home.css, src/pages/Home.js, src/pages/Join.css, src/pages/Join.js, src/pages/Login.css, src/pages/Login.js
=> 홈 로그인 회원가입 페이지

Dockerfile, Jenkinsfile, docker-compose.yml, nginx.conf, src/pages/Join.js, wowtown.sh
=> Feat: Add Jenkins CI/CD Pipeline

Jenkinsfile, docker-compose.yml
=> Fix: Change Jenkinfile and docker-compose

src/components/Channel.js, src/pages/Channels.js, src/pages/CharacterSettings.js, src/pages/Join.js, src/pages/Login.js
=> Feature 48 home edit

package-lock.json, package.json, src/apis/avatar.api.js, src/apis/axios.js, src/apis/channel.api.js, src/apis/user.api.js, src/components/Button.js, src/components/Channel.js, src/index.js, src/pages/Channels.js, src/pages/CharacterSettings.js, src/pages/Home.js, src/pages/Join.js, src/pages/Login.js, src/utils/AvatarState.js
=> refactoring apis

src/components/templates/SelectNotice.js, src/pages/ConnectMetaverse.js, src/pages/Notice.js
=> Add notice refresh logic

package-lock.json, package.json, src/apis/avatar.api.js, src/apis/axios.js, src/apis/channel.api.js, src/apis/chatRoom.api.js, src/apis/notice.api.js, src/components/atoms/Area.js, src/components/atoms/ChatFrame.js, src/components/atoms/Message.js, src/components/templates/ChannelList.js, src/components/templates/ChatList.js, src/components/templates/ChatRoom.js, src/components/templates/FrameHeader.js, src/components/templates/NoticeList.js, src/components/templates/PostNotice.js, src/components/templates/SelectNotice.js, src/pages/Chat.js, src/pages/ConnectMetaverse.js, src/pages/Login.js, src/pages/Notice.js
=> Feature 73 create chatting UI and connect api

src/App.js, src/apis/axios.js, src/apis/user.api.js, src/components/atoms/Area.js, src/components/templates/ChannelList.js, src/pages/Login.js, src/utils/History.js
- accessToken 만료시 서버에서 refreshToken이 유효하면 토큰 갱신
- refreshToken 만료시 localstorage 비우고 메인 홈으로 이동
close #91
=> Feat: Add authorization error handler

src/apis/avatar.api.js, src/pages/AvatarSettings.js
=> Bugfix avatarSettings

Jenkinsfile, src/apis/avatar.api.js, src/components/templates/PostNotice.js
=> Bugfix notice and Add emailSender API

src/apis/avatar.api.js, src/apis/axios.js, src/components/atoms/Area.js, src/components/atoms/InputInfo.js, src/components/templates/AvatarUpdateModal.js, src/components/templates/Modal.js, src/components/templates/Profile.js, src/pages/AvatarSettings.js, src/pages/ConnectMetaverse.js
=> Add avatar update modal

package-lock.json, package.json, src/apis/chatRoom.api.js, src/components/atoms/ChatFrame.js, src/components/atoms/Message.js, src/components/templates/ChatRoom.js
=> Add file or image/video transfer to chatroom

src/apis/chatRoom.api.js, src/components/atoms/AvatarFrame.js, src/components/templates/ChatRoom.js, src/components/templates/ChatRoomAvatarList.js, src/components/templates/FrameHeader.js, src/components/templates/NoticeDetail.js, src/components/templates/NoticeList.js, src/components/templates/PostNotice.js, src/components/templates/Profile.js, src/components/templates/SelectNotice.js
=> Add button to chatRoom for check avatar status

package-lock.json, package.json, src/App.js, src/components/templates/MeetingRoom.js, src/components/templates/Video.js
=> temp WebRTC

.gitignore, Dockerfile, Jenkinsfile, docker-compose.yml, nginx.conf, package-lock.json, package.json, src/apis/axios.js, src/components/atoms/ChatFrame.js, src/components/templates/ChatRoom.js
=> HTTPS Support

src/pages/ConnectMetaverse.js
=> Connect emailSend API

src/components/atoms/ChatFrame.js
=> Bugfix ChatFrame

src/components/templates/MeetingRoom.js
=> Change peer connection

src/components/templates/MeetingRoom.js
=> Add screenShare

src/App.js, src/apis/PrivateSpace.api.js, src/components/templates/ChatRoom.js, src/components/templates/MeetingRoom.js
=> Connect ChatRoom to PrivateSpace

src/components/templates/Video.js
=> Remove audio howling

src/components/atoms/AvatarFrame.js, src/components/atoms/Message.js, src/components/templates/ChatRoom.js, src/components/templates/MeetingRoom.js, src/components/templates/Profile.js
=> ChatRoom connection refactoring in privateSapce

src/components/atoms/ChatFrame.js, src/components/templates/ChatList.js
=> refactor chat

.github/dependabot.yml, src/components/templates/MeetingRoom.js
=> Feature 147 bugfix screen share

src/components/atoms/ChatFrame.js, src/components/atoms/ListFrame.js, src/components/atoms/StudyRoomFrame.js, src/components/templates/ChatList.js, src/components/templates/ChatRoom.js, src/components/templates/FriendList.js, src/components/templates/NoticeDetail.js, src/components/templates/NoticeList.js, src/components/templates/Profile.js, src/components/templates/StudyRoomList.js
=> Bugfix all components
